[2024-08-11T08:30:09.757+0000] {processor.py:161} INFO - Started process (PID=2987) to work on /home/ubuntu/zilloapi/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-11T08:30:09.757+0000] {processor.py:830} INFO - Processing file /home/ubuntu/zilloapi/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-11T08:30:09.759+0000] {logging_mixin.py:188} INFO - [2024-08-11T08:30:09.759+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/zilloapi/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-11T08:30:09.763+0000] {logging_mixin.py:188} INFO - [2024-08-11T08:30:09.761+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/zilloapi/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-11T08:30:09.763+0000] {logging_mixin.py:188} INFO - [2024-08-11T08:30:09.763+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-11T08:30:09.763+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/zilloapi/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-11T08:30:09.776+0000] {processor.py:183} INFO - Processing /home/ubuntu/zilloapi/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2024-08-11T08:31:00.341+0000] {processor.py:161} INFO - Started process (PID=3215) to work on /home/ubuntu/zilloapi/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-11T08:31:00.343+0000] {processor.py:830} INFO - Processing file /home/ubuntu/zilloapi/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-11T08:31:00.344+0000] {logging_mixin.py:188} INFO - [2024-08-11T08:31:00.344+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/zilloapi/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-11T08:31:00.346+0000] {logging_mixin.py:188} INFO - [2024-08-11T08:31:00.346+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/zilloapi/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-11T08:31:00.347+0000] {logging_mixin.py:188} INFO - [2024-08-11T08:31:00.346+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-11T08:31:00.347+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/zilloapi/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-11T08:31:00.355+0000] {processor.py:183} INFO - Processing /home/ubuntu/zilloapi/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2024-08-11T08:31:49.404+0000] {processor.py:161} INFO - Started process (PID=3274) to work on /home/ubuntu/zilloapi/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-11T08:31:49.406+0000] {processor.py:830} INFO - Processing file /home/ubuntu/zilloapi/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-11T08:31:49.408+0000] {logging_mixin.py:188} INFO - [2024-08-11T08:31:49.407+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/zilloapi/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-11T08:31:49.411+0000] {logging_mixin.py:188} INFO - [2024-08-11T08:31:49.410+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/zilloapi/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-11T08:31:49.411+0000] {logging_mixin.py:188} INFO - [2024-08-11T08:31:49.411+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-11T08:31:49.411+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/zilloapi/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-11T08:31:49.421+0000] {processor.py:183} INFO - Processing /home/ubuntu/zilloapi/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2024-08-11T08:32:49.954+0000] {processor.py:161} INFO - Started process (PID=3336) to work on /home/ubuntu/zilloapi/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-11T08:32:49.956+0000] {processor.py:830} INFO - Processing file /home/ubuntu/zilloapi/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-11T08:32:49.958+0000] {logging_mixin.py:188} INFO - [2024-08-11T08:32:49.957+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/zilloapi/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-11T08:32:49.961+0000] {logging_mixin.py:188} INFO - [2024-08-11T08:32:49.960+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/zilloapi/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-11T08:32:49.961+0000] {logging_mixin.py:188} INFO - [2024-08-11T08:32:49.961+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-11T08:32:49.961+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/zilloapi/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-11T08:32:49.972+0000] {processor.py:183} INFO - Processing /home/ubuntu/zilloapi/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2024-08-11T08:33:45.942+0000] {processor.py:161} INFO - Started process (PID=3397) to work on /home/ubuntu/zilloapi/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-11T08:33:45.945+0000] {processor.py:830} INFO - Processing file /home/ubuntu/zilloapi/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-11T08:33:45.947+0000] {logging_mixin.py:188} INFO - [2024-08-11T08:33:45.946+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/zilloapi/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-11T08:33:45.949+0000] {logging_mixin.py:188} INFO - [2024-08-11T08:33:45.949+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/zilloapi/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-11T08:33:45.950+0000] {logging_mixin.py:188} INFO - [2024-08-11T08:33:45.949+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-11T08:33:45.950+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/zilloapi/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-11T08:33:45.961+0000] {processor.py:183} INFO - Processing /home/ubuntu/zilloapi/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2024-08-11T08:34:46.397+0000] {processor.py:161} INFO - Started process (PID=3465) to work on /home/ubuntu/zilloapi/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-11T08:34:46.399+0000] {processor.py:830} INFO - Processing file /home/ubuntu/zilloapi/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-11T08:34:46.400+0000] {logging_mixin.py:188} INFO - [2024-08-11T08:34:46.400+0000] {dagbag.py:545} INFO - Filling up the DagBag from /home/ubuntu/zilloapi/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-11T08:34:46.403+0000] {logging_mixin.py:188} INFO - [2024-08-11T08:34:46.403+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ubuntu/zilloapi/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-11T08:34:46.403+0000] {logging_mixin.py:188} INFO - [2024-08-11T08:34:46.403+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-11T08:34:46.403+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/zilloapi/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-11T08:34:46.413+0000] {processor.py:183} INFO - Processing /home/ubuntu/zilloapi/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
